// Centralized, themeable styles for the dashboard page.

const baseTheme = {
  label: "Classic",
  colors: {
    pageBg: "#f3f6fb",
    panelBg: "#ffffff",
    cardBg: "#ffffff",
    border: "#d8e0ef",
    borderSoft: "#eef2fb",
    text: "#1f2937",
    mutedText: "#666666",
    primary: "#0b6b2a",
    primaryText: "#ffffff",
    badgeBg: "#eef2fb",
    badgeText: "#333333",
    pillBg: "#f7f9ff",
    errorBg: "#fff3f3",
    errorBorder: "#ffd2d2",
    errorText: "#a40000",
  },
  radius: {
    card: 18,
    panel: 18,
    input: 12,
    button: 12,
    tab: 999,
    pill: 999,
    badge: 999,
  },
  shadow: "0 10px 30px rgba(0,0,0,0.05)",
  fontFamily: "system-ui, -apple-system, Segoe UI, Roboto, Arial, sans-serif",
};

export const themePresets = {
  classic: baseTheme,
  clean: {
    ...baseTheme,
    label: "Clean",
    colors: {
      ...baseTheme.colors,
      pageBg: "#f7f8fb",
      border: "#e5e9f2",
      borderSoft: "#f0f3f8",
      primary: "#2563eb",
      pillBg: "#eef2ff",
    },
    shadow: "0 6px 20px rgba(15, 23, 42, 0.08)",
  },
  dark: {
    ...baseTheme,
    label: "Dark",
    colors: {
      pageBg: "#0f172a",
      panelBg: "#111827",
      cardBg: "#1f2937",
      border: "#334155",
      borderSoft: "#1f2a44",
      text: "#e5e7eb",
      mutedText: "#9ca3af",
      primary: "#38bdf8",
      primaryText: "#0b1120",
      badgeBg: "#111827",
      badgeText: "#e5e7eb",
      pillBg: "#1e293b",
      errorBg: "#2b1115",
      errorBorder: "#7f1d1d",
      errorText: "#fca5a5",
    },
    shadow: "0 14px 40px rgba(0,0,0,0.4)",
  },
  corporate: {
    ...baseTheme,
    label: "Corporate",
    colors: {
      ...baseTheme.colors,
      pageBg: "#eef2f6",
      primary: "#1f3b73",
      primaryText: "#ffffff",
      badgeBg: "#e0e7f4",
      pillBg: "#e8eef9",
    },
    radius: {
      ...baseTheme.radius,
      card: 10,
      panel: 10,
      input: 8,
      button: 8,
    },
  },
  soft: {
    ...baseTheme,
    label: "Soft",
    colors: {
      ...baseTheme.colors,
      pageBg: "#fff8f3",
      panelBg: "#fffefc",
      cardBg: "#ffffff",
      border: "#f5d9cc",
      borderSoft: "#fde9df",
      primary: "#f97316",
      primaryText: "#ffffff",
      badgeBg: "#fde9df",
      pillBg: "#fff1e6",
    },
    radius: {
      ...baseTheme.radius,
      card: 22,
      panel: 22,
      input: 16,
      button: 16,
    },
    shadow: "0 12px 35px rgba(249, 115, 22, 0.12)",
  },
};

const FALLBACK_KEY = "classic";

export function getStyles(themeKey = FALLBACK_KEY) {
  const theme = themePresets[themeKey] || themePresets[FALLBACK_KEY];
  const { colors, radius, shadow, fontFamily } = theme;

  return {
    page: {
      minHeight: "100vh",
      background: colors.pageBg,
      padding: 18,
      fontFamily,
      color: colors.text,
    },
    topbar: {
      display: "flex",
      gap: 14,
      alignItems: "center",
      justifyContent: "space-between",
      marginBottom: 14,
    },
    brand: {
      fontSize: 30,
      fontWeight: 800,
      letterSpacing: -0.5,
      color: colors.text,
    },
    tabs: {
      display: "flex",
      gap: 10,
      alignItems: "center",
      flexWrap: "wrap",
    },
    tab: {
      border: `1px solid ${colors.border}`,
      background: colors.panelBg,
      padding: "10px 14px",
      borderRadius: radius.tab,
      cursor: "pointer",
      fontWeight: 600,
      color: colors.text,
    },
    tabActive: {
      background: colors.primary,
      borderColor: colors.primary,
      color: colors.primaryText,
    },
    right: {
      display: "flex",
      gap: 12,
      alignItems: "center",
    },
    panel: {
      background: colors.panelBg,
      border: `1px solid ${colors.border}`,
      borderRadius: radius.panel,
      padding: 16,
      boxShadow: shadow,
      marginBottom: 14,
    },
    h3: {
      fontSize: 18,
      fontWeight: 800,
      marginBottom: 10,
      color: colors.text,
    },
    h4: {
      fontSize: 16,
      fontWeight: 800,
      marginBottom: 4,
      color: colors.text,
    },
    rowBetween: {
      display: "flex",
      alignItems: "center",
      justifyContent: "space-between",
      gap: 12,
    },
    columns: {
      display: "grid",
      gridTemplateColumns: "1fr 1fr",
      gap: 14,
    },
    col: {
      background: "transparent",
    },
    colHeader: {
      display: "flex",
      alignItems: "center",
      justifyContent: "space-between",
      marginBottom: 10,
    },
    badge: {
      minWidth: 28,
      height: 28,
      borderRadius: radius.badge,
      background: colors.badgeBg,
      border: `1px solid ${colors.border}`,
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      fontWeight: 700,
      color: colors.badgeText,
    },
    pill: {
      fontSize: 12,
      padding: "4px 10px",
      borderRadius: radius.pill,
      border: `1px solid ${colors.border}`,
      background: colors.pillBg,
      fontWeight: 700,
      color: colors.text,
    },
    card: {
      background: colors.cardBg,
      border: `1px solid ${colors.border}`,
      borderRadius: radius.card,
      padding: 14,
      boxShadow: shadow,
    },
    input: {
      padding: 10,
      borderRadius: radius.input,
      border: `1px solid ${colors.border}`,
      outline: "none",
      background: colors.panelBg,
      minWidth: 160,
      color: colors.text,
    },
    textarea: {
      padding: 10,
      borderRadius: radius.input,
      border: `1px solid ${colors.border}`,
      outline: "none",
      background: colors.panelBg,
      width: "100%",
      resize: "vertical",
      color: colors.text,
    },
    btn: {
      padding: "10px 14px",
      borderRadius: radius.button,
      border: `1px solid ${colors.border}`,
      background: colors.panelBg,
      cursor: "pointer",
      fontWeight: 700,
      color: colors.text,
    },
    btnPrimary: {
      padding: "10px 14px",
      borderRadius: radius.button,
      border: `1px solid ${colors.primary}`,
      background: colors.primary,
      color: colors.primaryText,
      cursor: "pointer",
      fontWeight: 800,
    },
    error: {
      background: colors.errorBg,
      border: `1px solid ${colors.errorBorder}`,
      color: colors.errorText,
      padding: 12,
      borderRadius: radius.input,
      marginTop: 10,
      marginBottom: 10,
    },
    taskFormGrid: {
      display: "grid",
      gridTemplateColumns: "1.2fr 1fr 1fr 1fr 1.2fr auto",
      gap: 10,
      alignItems: "start",
    },
    table: {
      width: "100%",
      borderCollapse: "collapse",
    },
    th: {
      textAlign: "left",
      padding: 10,
      borderBottom: `1px solid ${colors.border}`,
      fontSize: 13,
      color: colors.mutedText,
    },
    td: {
      padding: 10,
      borderBottom: `1px solid ${colors.borderSoft}`,
      verticalAlign: "top",
    },
  };
}
